### ISSUE TITLE
server locks up

### ISSUE THREAD

**Issue by rberiot** [gdesmott/karapulse#21] opened 2019-03-06 14:00 UTC
last server logs:
`[2019-03-06T13:21:24Z INFO  rocket::rocket] GET /api/status/ application/json:
[2019-03-06T13:21:29Z INFO  rocket::rocket] GET /api/status/ application/json:
[2019-03-06T13:21:29Z INFO  rocket::rocket] GET /api/search/caca application/json:
[2019-03-06T13:21:32Z INFO  rocket::rocket] GET /api/enqueue_db/77651/JZOGEOHGEO application/json:
[2019-03-06T13:21:34Z INFO  rocket::rocket] GET /api/status/ application/json:
[2019-03-06T13:21:34Z INFO  rocket::rocket] GET /api/enqueue_db/77651/JZOGEOHGEO application/json:
[2019-03-06T13:21:37Z INFO  rocket::rocket] GET /api/status/ application/json:
[2019-03-06T13:21:39Z INFO  rocket::rocket] GET /api/status/ application/json:
[2019-03-06T13:21:44Z INFO  rocket::rocket] GET /api/status/ application/json:
[2019-03-06T13:21:49Z INFO  rocket::rocket] GET /api/status/ application/json:
[2019-03-06T13:21:54Z INFO  rocket::rocket] GET /api/status/ application/json:
[2019-03-06T13:21:55Z INFO  rocket::rocket] GET /api/enqueue_db/77651/JZOGEOHGEO application/json:
`
thread dump : https://pastebin.com/62N4UEfc

**Comment by gdesmott** [comment] 2019-03-06 16:18
Tricky as I don't understand the root cause of the lock.

Anyway, I just pushed a couple of patches that should workaround it. Please test with `RUST_LOG=karapulse=trace,rocket=trace` and let me know if you can reproduce or see warnings in the debug output.

**Comment by gdesmott** [comment] 2019-03-07 10:52
I **think** it should be ok now with:

- https://github.com/gdesmott/karapulse/commit/e4c3a1da6d91cb21a0dce24e8a706a1361f1bcd6
- https://github.com/gdesmott/karapulse/commit/d16a8a3381fef704fc3a5f3bcd5a950c03a9f065
- https://github.com/gdesmott/karapulse/commit/090a52b8bf8c2a5b1f0bcfc96ab503859aef43be

Let's close it for now and re-open if needed.

**Closed by gdesmott** 2019-03-07 10:52 UTC
Labels: blocker
